# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
Data models for the My Env Environment.

The my_env environment models a complaint-resolution conversation where an
agent responds to a customer's complaint and receives reward from customer
feedback.
"""

from openenv.core.env_server.types import Action, Observation, State
from pydantic import Field, model_validator


class MyAction(Action):
    """Action for the complaint environment."""

    agent_message: str | None = Field(
        default=None,
        description="Reply generated by the support agent for the customer's complaint",
    )
    customer_message: str | None = Field(
        default=None,
        description=(
            "Optional free-form customer message. Use this when the real client "
            "responds in a later turn."
        ),
    )
    client_feedback: str | None = Field(
        default=None,
        description=(
            "Deprecated alias for customer_message. If omitted, the environment "
            "can simulate customer feedback."
        ),
    )
    feedback_score: float | None = Field(
        default=None,
        ge=-1.0,
        le=1.0,
        description=(
            "Optional explicit reward hint from the client in the range [-1, 1]. "
            "Positive means the reply helped, negative means it was unhelpful."
        ),
    )
    mark_resolved: bool | None = Field(
        default=None,
        description="Optional human signal that the complaint has been resolved",
    )
    await_customer_response: bool = Field(
        default=False,
        description=(
            "When true, the environment records the agent reply and waits for a "
            "future customer_message instead of simulating feedback immediately."
        ),
    )

    @model_validator(mode="after")
    def validate_turn_payload(self) -> "MyAction":
        if not any(
            (
                self.agent_message and self.agent_message.strip(),
                self.customer_message and self.customer_message.strip(),
                self.client_feedback and self.client_feedback.strip(),
            )
        ):
            raise ValueError(
                "Provide at least one of agent_message, customer_message, or client_feedback."
            )
        return self


class MyObservation(Observation):
    """Observation returned after each complaint-resolution step."""

    task_id: str = Field(default="", description="Benchmark task identifier")
    task_name: str = Field(default="", description="Human-readable task name")
    task_difficulty: str = Field(
        default="medium", description="Relative task difficulty label"
    )
    complaint_id: str = Field(default="", description="Unique complaint identifier")
    complaint_category: str = Field(
        default="", description="Complaint category such as billing or delivery"
    )
    complaint_text: str = Field(
        default="", description="Original customer complaint for this episode"
    )
    latest_customer_message: str = Field(
        default="",
        description="Most recent customer-facing message, including complaint or feedback",
    )
    latest_agent_message: str = Field(
        default="", description="Most recent message sent by the support agent"
    )
    customer_sentiment: str = Field(
        default="neutral",
        description="Environment estimate of the customer's latest sentiment",
    )
    satisfaction_score: float = Field(
        default=0.0,
        description="Running customer satisfaction score accumulated during the episode",
    )
    resolution_status: str = Field(
        default="open",
        description="Current resolution status: open, in_progress, resolved, or escalated",
    )
    suggested_next_action: str = Field(
        default="",
        description="Guidance for the next agent step if the complaint is still open",
    )
    chat_history: list[str] = Field(
        default_factory=list,
        description="Compact transcript of the conversation so far",
    )
    awaiting_customer_response: bool = Field(
        default=False,
        description="Whether the environment is waiting for a real customer reply",
    )
    grader_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description=(
            "Deterministic benchmark score for the current task. The terminal score "
            "is always clamped strictly inside the interval (0, 1)."
        ),
    )


class MyState(State):
    """Internal state for the complaint-resolution environment."""

    complaint_id: str = Field(default="", description="Unique complaint identifier")
    complaint_category: str = Field(default="", description="Complaint category")
    satisfaction_score: float = Field(
        default=0.0, description="Current accumulated satisfaction score"
    )
    resolution_status: str = Field(
        default="open", description="Current resolution state of the episode"
    )
    last_customer_sentiment: str = Field(
        default="neutral", description="Latest known customer sentiment"
    )
    awaiting_customer_response: bool = Field(
        default=False, description="Whether a pending agent reply awaits customer feedback"
    )
    pending_agent_message: str = Field(
        default="", description="Most recent agent reply waiting on customer feedback"
    )
    pending_judge_score: float = Field(
        default=0.0, description="Heuristic score for the pending agent reply"
    )
