"""Per-websocket AI chat session built on OpenAI and MyEnv."""

from __future__ import annotations

import os
import textwrap
from typing import Optional

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field

try:
    from ... import MyAction, MyEnv
except ImportError:
    from client import MyEnv
    from models import MyAction

from ..sql.db import get_chat_by_key

load_dotenv()


class AIModelStepResult(BaseModel):
    """Result returned after processing one customer message."""

    assistant_text: str = Field(..., description="Assistant reply generated by the model")
    reward: float = Field(default=0.0, description="Latest reward from the environment")
    resolution_status: str = Field(default="open", description="Environment resolution status")
    customer_sentiment: str = Field(default="neutral", description="Latest customer sentiment")
    satisfaction_score: float = Field(default=0.0, description="Running satisfaction score")
    awaiting_customer_response: bool = Field(
        default=False,
        description="Whether the environment is now waiting for another customer reply",
    )
    done: bool = Field(default=False, description="Whether the environment episode is done")


class AIModelSession:
    """Owns one OpenAI client and one MyEnv session for a websocket chat."""

    def __init__(self, chat_key: str):
        self.chat_key = chat_key
        self.api_base_url = os.getenv("API_BASE_URL") or "https://api.openai.com/v1"
        self.model_name = os.getenv("MODEL_NAME") or "gpt-4o-mini"
        self.api_key = (
            os.getenv("OPENAI_API_KEY")
            or os.getenv("HF_TOKEN")
            or os.getenv("API_KEY")
        )
        self.env_base_url = (
            os.getenv("CHAT_ENV_BASE_URL")
            or os.getenv("INTERNAL_ENV_BASE_URL")
            or os.getenv("ENV_BASE_URL")
            or f"http://127.0.0.1:{os.getenv('PORT', '8000')}"
        )
        self.temperature = float(os.getenv("TEMPERATURE", "0.3"))
        self.max_tokens = int(os.getenv("MAX_TOKENS", "512"))
        self.client = OpenAI(base_url=self.api_base_url, api_key=self.api_key)
        self.env: Optional[MyEnv] = None
        self.initialized = False
        self.last_reward = 0.0

    async def _ensure_env(self) -> MyEnv:
        if self.env is None:
            env = MyEnv(base_url=self.env_base_url)
            await env.connect()
            self.env = env
        return self.env

    async def close(self) -> None:
        if self.env is not None:
            await self.env.close()
            self.env = None

    async def step(self, customer_message: str) -> AIModelStepResult:
        env = await self._ensure_env()

        if not self.initialized:
            chat_meta = get_chat_by_key(self.chat_key) or {}
            result = await env.reset(
                complaint_id=f"chat-{self.chat_key}",
                complaint_category="service",
                complaint_text=customer_message,
                customer_name=str(chat_meta.get("customer_name") or "Customer"),
            )
            self.initialized = True
        else:
            result = await env.step(MyAction(customer_message=customer_message))

        observation = result.observation
        self.last_reward = float(result.reward or 0.0)

        assistant_text = self._generate_assistant_reply(observation.model_dump())
        assistant_result = await env.step(
            MyAction(agent_message=assistant_text, await_customer_response=True)
        )
        assistant_observation = assistant_result.observation

        return AIModelStepResult(
            assistant_text=assistant_text,
            reward=self.last_reward,
            resolution_status=assistant_observation.resolution_status,
            customer_sentiment=assistant_observation.customer_sentiment,
            satisfaction_score=assistant_observation.satisfaction_score,
            awaiting_customer_response=assistant_observation.awaiting_customer_response,
            done=assistant_result.done,
        )

    def _generate_assistant_reply(self, observation: dict[str, object]) -> str:
        history = observation.get("chat_history", [])
        if isinstance(history, list):
            history_block = "\n".join(str(item) for item in history[-8:]) if history else "None"
        else:
            history_block = "None"

        prompt = textwrap.dedent(
            f"""
            Complaint category: {observation.get("complaint_category", "")}
            Original complaint: {observation.get("complaint_text", "")}
            Latest customer message: {observation.get("latest_customer_message", "")}
            Customer sentiment: {observation.get("customer_sentiment", "neutral")}
            Satisfaction score: {observation.get("satisfaction_score", 0.0)}
            Resolution status: {observation.get("resolution_status", "open")}
            Last reward: {self.last_reward:.2f}
            Suggested next action: {observation.get("suggested_next_action", "")}
            Recent transcript:
            {history_block}
            Write the next support reply.
            """
        ).strip()

        fallback = (
            "I am sorry for the inconvenience. I will review your complaint and provide "
            "a clear next step right away."
        )

        try:
            completion = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a customer support agent. Reply with one empathetic, "
                            "specific, actionable support message."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                temperature=self.temperature,
                max_tokens=self.max_tokens,
                stream=False,
            )
            text = (completion.choices[0].message.content or "").strip()
            return text or fallback
        except Exception:
            return fallback
